# Base: runtime dependencies only, shared by the runtime and test images.
# Pinned to an exact digest for reproducibility (see #40).
FROM python:3.12-slim@sha256:dddfd7e07f9d15aeeca61529320492139d21cac7f0070c00609243e51e4e0016 AS base

WORKDIR /app

# Install dependencies first for better layer caching. The lockfile is
# generated by pip-compile (see requirements.lock header) and installed with
# --require-hashes so transitive dependencies are pinned too.
COPY requirements.lock .
RUN pip install --no-cache-dir --require-hashes -r requirements.lock

# Test image: adds dev dependencies and the test suite. `source/` is copied as
# a directory (not flattened) so `pythonpath = ["source"]` in pyproject.toml
# resolves identically here and in local development.
FROM base AS test

COPY requirements-dev.lock .
RUN pip install --no-cache-dir --require-hashes -r requirements-dev.lock
COPY pyproject.toml .
COPY source/ source/
COPY tests/ tests/

# Runtime image: the gateway as a user runs it.
FROM base AS runtime

COPY source/ .

# The gateway listens on a fixed port 8000 inside the container; the compose
# files map a host port onto it (see `PORT` in `.env.example`).
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
