"""Generate ``.env.example`` and ``docs/configuration.md`` from ``config.py``.

The single source of truth for application configuration is
:class:`app.config.Settings`. This module renders that model into the two
derived artefacts so they cannot drift. Compose-level variables (``PORT``,
``UID``, ``GID``) are read directly by Docker Compose — not the application —
and are therefore listed explicitly below rather than on ``Settings``.
"""

from __future__ import annotations

from typing import Any

from pydantic.fields import FieldInfo

from app.config import Settings

# Compose-level variables read by docker-compose.yml / docker-compose.dev.yml,
# not by the application. Documented here so `.env.example` is complete.
COMPOSE_VARS: tuple[tuple[str, str, str], ...] = (
    (
        "PORT",
        "9317",
        "Host port the gateway is published on (compose `ports:` mapping only). "
        "The gateway always listens on port 8000 inside the container.",
    ),
    (
        "UID",
        "1000",
        "Host user ID the container runs as, so the bind-mounted `data/` directory "
        "stays writable and owned by you. Defaults to 1000 when unset.",
    ),
    (
        "GID",
        "1000",
        "Host group ID the container runs as, so the bind-mounted `data/` directory "
        "stays writable and owned by you. Defaults to 1000 when unset.",
    ),
)


def _render(value: Any) -> str:
    """Render a default value for the generated files."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _grouped_fields() -> list[tuple[str, list[tuple[str, FieldInfo]]]]:
    """Return ``Settings`` fields grouped by section, in declaration order."""
    groups: dict[str, list[tuple[str, FieldInfo]]] = {}
    order: list[str] = []
    for name, info in Settings.model_fields.items():
        extra = info.json_schema_extra
        section = str(extra.get("section", "Other")) if isinstance(extra, dict) else "Other"
        if section not in groups:
            groups[section] = []
            order.append(section)
        groups[section].append((name, info))
    return [(section, groups[section]) for section in order]


def env_example() -> str:
    """Render the contents of ``.env.example``."""
    lines: list[str] = [
        "# Generated by scripts/generate_config.py from source/app/config.py.",
        "# Do not edit by hand; edit config.py and re-run the generator.",
        "",
    ]
    lines.append("# --- Deployment (Docker Compose) ---")
    for name, default, description in COMPOSE_VARS:
        lines.append(f"# {description}")
        lines.append(f"{name}={default}")
        lines.append("")
    for section, fields in _grouped_fields():
        lines.append(f"# --- {section} ---")
        for name, info in fields:
            lines.append(f"# {info.description or ''}")
            lines.append(f"{name.upper()}={_render(info.default)}")
            lines.append("")
    return "\n".join(lines)


def configuration_md() -> str:
    """Render the contents of ``docs/configuration.md``."""
    lines: list[str] = [
        "# Configuration",
        "",
        "llm-gauze is configured entirely through environment variables (read from",
        "`.env`). Copy `.env.example` to `.env` and adjust. Every setting is listed",
        "below, grouped by feature, with its default.",
        "",
        "> This file is generated by `scripts/generate_config.py` from",
        "> `source/app/config.py`. Do not edit by hand; edit `config.py` and re-run",
        "> the generator.",
        "",
    ]

    def _section(title: str, rows: list[tuple[str, str, str]]) -> None:
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Variable | Default | Description |")
        lines.append("| --- | --- | --- |")
        for name, default, description in rows:
            lines.append(f"| `{name}` | `{default}` | {description} |")
        lines.append("")

    compose_rows = [(name, default, description) for name, default, description in COMPOSE_VARS]
    _section("Deployment (Docker Compose)", compose_rows)

    for section, fields in _grouped_fields():
        rows = [
            (name.upper(), _render(info.default), info.description or "") for name, info in fields
        ]
        _section(section, rows)

    # Drop the trailing blank line added by the last _section call.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"
